// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0kmBAaohB39bHp7pYZaVUKNd5Ub-htGs',
    appId: '1:505201158498:web:252487950cdd733b29e43b',
    messagingSenderId: '505201158498',
    projectId: 'waste-management-app-4de40',
    authDomain: 'waste-management-app-4de40.firebaseapp.com',
    storageBucket: 'waste-management-app-4de40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBbpa9u1fuwWq5ubE75nNH3q06SJ-y7n4',
    appId: '1:505201158498:android:35691d14cef6eb9b29e43b',
    messagingSenderId: '505201158498',
    projectId: 'waste-management-app-4de40',
    storageBucket: 'waste-management-app-4de40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-HF82Ob6EfxoC7nBfuda1-nRIfp5FoQ',
    appId: '1:505201158498:ios:3f36a862770ab52329e43b',
    messagingSenderId: '505201158498',
    projectId: 'waste-management-app-4de40',
    storageBucket: 'waste-management-app-4de40.firebasestorage.app',
    iosBundleId: 'com.example.wasteAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-HF82Ob6EfxoC7nBfuda1-nRIfp5FoQ',
    appId: '1:505201158498:ios:3f36a862770ab52329e43b',
    messagingSenderId: '505201158498',
    projectId: 'waste-management-app-4de40',
    storageBucket: 'waste-management-app-4de40.firebasestorage.app',
    iosBundleId: 'com.example.wasteAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0kmBAaohB39bHp7pYZaVUKNd5Ub-htGs',
    appId: '1:505201158498:web:af96906a8d3d2c8329e43b',
    messagingSenderId: '505201158498',
    projectId: 'waste-management-app-4de40',
    authDomain: 'waste-management-app-4de40.firebaseapp.com',
    storageBucket: 'waste-management-app-4de40.firebasestorage.app',
  );
}
